#!/bin/bash

ARG1=$1
ARG2=$2
FHOST_VERSION="0.1"
FHOST_BUILD="0.1.2"
OS=""

if [[ $EUID -ne 0 ]]; then
    echo "FHost requires root privileges"
    exit 1
fi

source /etc/os-release
if [ "$ID" == "debian" ] && [ "$VERSION_ID" == "10" ]; then
    OS="debian10"
elif [ "$ID" == "debian" ] && [ "$VERSION_ID" == "9" ]; then
    OS="debian9"
fi

################## BEGIN - INSTALL SERVER ##################
if [ "$ARG1" == "install" ] && [ "$ARG2" == "server" ]; then
    if [ "$OS" == "debian10" ] || [ "$OS" == "debian9" ]; then
        apt update
        apt -y install apache2 php mariadb-server
        mysql_secure_installation

        ./fhost install client
    fi
################## END - INSTALL SERVER ##################

################## BEGIN - INSTALL CLIENT ##################
elif [ "$ARG1" == "install" ] && [ "$ARG2" == "client" ]; then
    mkdir -p /var/www/fhost
    mkdir -p /etc/fhost
    mkdir -p /etc/fhost/templates
    touch /etc/fhost/fhost.log
    touch /etc/fhost/vhosts

    cp ./fhost /bin/fhost
	chown root:root /bin/fhost
	chmod 770 /bin/fhost

    echo ""
    echo "FHOST INSTALLED"
    echo ""
################## END - INSTALL CLIENT ##################


################## BEGIN - UNINSTALL CLIENT ##################
elif [ "$ARG1"  == "uninstall" ] && [ "$ARG2" == "client" ]; then

    rm /bin/fhost

    echo ""
    echo "FHOST UNINSTALLED"
    echo ""
################## END - UNINSTALL CLIENT ##################


################## BEGIN - VERSION ##################
elif [ "$ARG1" == "version" ] || [ "$ARG1" == "-v" ] || \
     [ "$ARG1" == "--version" ] || [ "$ARG1" == "-version" ] || \
     [ "$ARG1" == "--v" ]; then

    echo -e "\nFHost - Version: $FHOST_VERSION\n"
    echo -e "Fast Hosting Management\n"

################## END - VERSION ##################

else
    echo -e "\nFHost - Version: $FHOST_VERSION\n"
    echo -e "Fast Hosting Management\n"
fi
